default_content_extra.settings:
  type: config_object
  label: 'Default Content Extra Settings'
  mapping:
    path_alias:
      type: integer
      label: 'Path Alias'
    delete_users:
      type: integer
      label: 'Delete Users 0 and 1'
